# Start with the official Airflow image
FROM apache/airflow:2.10.4

# Set environment variables
ENV AIRFLOW_HOME=/opt/airflow
ENV PYTHONPATH=/opt/airflow

# Copy the entire project directory into the container
COPY ./ /opt/airflow

# Set the working directory
WORKDIR /opt/airflow

# Install PostgreSQL client library
RUN pip install psycopg2-binary

# Switch to root user for permissions and cleanup
USER root

# Ensure build directory is writable and remove it if it exists
RUN chmod -R u+w build/ && rm -rf build/

# Switch back to airflow user before running pip install
USER airflow

# Install the custom module
RUN pip install .

# Install system dependencies required by the project
USER root
RUN apt-get update && apt-get install -y libgomp1 && apt-get clean && rm -rf /var/lib/apt/lists/*

# Switch back to airflow user
USER airflow

# Copy the requirements file into the container
COPY ./Requirements.txt /opt/airflow/Requirements.txt

# Install Python dependencies from requirements.txt
RUN pip install --no-cache-dir -r /opt/airflow/Requirements.txt

# Copy DAGs into the Airflow container
COPY ./dags /opt/airflow/dags

#COPY ./fordockerenv.txt /opt/airflow/.env

ENV MLFLOW_TRACKING_URI=/opt/airflow/mlruns

# Expose ports for the Airflow webserver
EXPOSE 8080

# Command to start Airflow (only for standalone setups)
CMD ["standalone"]
